---
- name: copy job_conf.xml
  become: yes
  become_user: "{{ galaxy_user_name }}"
  copy: src=job_conf.xml dest={{ galaxy_config_dir }}

- name: install gridengine packages
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - gridengine-client
    - gridengine-drmaa1.0
    - gridengine-drmaa-dev

- name: mount gridengine state directory
  become: yes
  become_user: root
  mount: name=/var/lib/gridengine/default/common src=grid00.sanbi.ac.za:/var/lib/gridengine/default/common state=mounted fstype=nfs

- name: install the python drmaa module
  become: yes
  become_user: "{{ galaxy_user_name }}"
  pip: name=drmaa virtualenv={{ galaxy_venv_dir }}
